version: '3'
services:
  api:
    build: .
    command: sh -c "npm install && npm run start:dev"
    volumes:
      - .:/api
    ports:
      - '8080:8080'
      - '9229:9229'
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:11-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=lunchwatch
      - POSTGRES_PASSWORD=lunchwatch
      - POSTGRES_DB=lunchwatch
